SEED_WORDS = [
    # === TECH (30 words) ===
    {"word": "PYTHON", "hint": "Linguagem de programação com sintaxe limpa", "category": "tech", "difficulty": 1},
    {"word": "JAVA", "hint": "Linguagem usada em aplicativos Android", "category": "tech", "difficulty": 1},
    {"word": "CLOUD", "hint": "Computação em nuvem", "category": "tech", "difficulty": 1},
    {"word": "PIXEL", "hint": "Menor unidade de uma imagem digital", "category": "tech", "difficulty": 1},
    {"word": "BYTE", "hint": "Unidade de dados de 8 bits", "category": "tech", "difficulty": 1},
    {"word": "WIFI", "hint": "Conexão sem fio à internet", "category": "tech", "difficulty": 1},
    {"word": "ALGORITHM", "hint": "Sequência de passos para resolver um problema", "category": "tech", "difficulty": 2},
    {"word": "DATABASE", "hint": "Banco de dados estruturado", "category": "tech", "difficulty": 2},
    {"word": "COMPILER", "hint": "Programa que traduz código-fonte", "category": "tech", "difficulty": 2},
    {"word": "FIREWALL", "hint": "Barreira de segurança de rede", "category": "tech", "difficulty": 2},
    {"word": "KEYBOARD", "hint": "Dispositivo de entrada de texto", "category": "tech", "difficulty": 2},
    {"word": "NETWORK", "hint": "Sistema de computadores conectados", "category": "tech", "difficulty": 2},
    {"word": "BROWSER", "hint": "Programa para navegar na internet", "category": "tech", "difficulty": 2},
    {"word": "PROGRAM", "hint": "Conjunto de instruções de computador", "category": "tech", "difficulty": 2},
    {"word": "MONITOR", "hint": "Tela que exibe a saída do computador", "category": "tech", "difficulty": 1},
    {"word": "ROUTER", "hint": "Dispositivo que direciona dados em rede", "category": "tech", "difficulty": 2},
    {"word": "SYNTAX", "hint": "Regras gramaticais de uma linguagem", "category": "tech", "difficulty": 3},
    {"word": "VARIABLE", "hint": "Espaço de memória com nome", "category": "tech", "difficulty": 3},
    {"word": "FUNCTION", "hint": "Bloco de código reutilizável", "category": "tech", "difficulty": 3},
    {"word": "LOOP", "hint": "Estrutura de repetição", "category": "tech", "difficulty": 1},
    {"word": "ARRAY", "hint": "Coleção ordenada de elementos", "category": "tech", "difficulty": 2},
    {"word": "KERNEL", "hint": "Núcleo do sistema operacional", "category": "tech", "difficulty": 3},
    {"word": "THREAD", "hint": "Unidade de execução dentro de um processo", "category": "tech", "difficulty": 3},
    {"word": "MODERN", "hint": "Estilo de desenvolvimento web atual", "category": "tech", "difficulty": 2},
    {"word": "SERVER", "hint": "Computador que fornece serviços", "category": "tech", "difficulty": 1},
    {"word": "MOUSE", "hint": "Dispositivo de apontamento", "category": "tech", "difficulty": 1},
    {"word": "CACHE", "hint": "Armazenamento temporário de dados", "category": "tech", "difficulty": 3},
    {"word": "DEBUG", "hint": "Processo de encontrar erros no código", "category": "tech", "difficulty": 2},
    {"word": "STACK", "hint": "Estrutura de dados LIFO", "category": "tech", "difficulty": 3},
    {"word": "TOKEN", "hint": "Elemento básico de análise léxica", "category": "tech", "difficulty": 3},

    # === ANIMALS (30 words) ===
    {"word": "LION", "hint": "Rei da selva", "category": "animals", "difficulty": 1},
    {"word": "BEAR", "hint": "Grande mamífero que hiberna", "category": "animals", "difficulty": 1},
    {"word": "WOLF", "hint": "Canino selvagem que vive em matilhas", "category": "animals", "difficulty": 1},
    {"word": "FROG", "hint": "Anfíbio que pula e croa", "category": "animals", "difficulty": 1},
    {"word": "DEER", "hint": "Cervídeo com chifres", "category": "animals", "difficulty": 1},
    {"word": "WHALE", "hint": "Maior animal do planeta", "category": "animals", "difficulty": 1},
    {"word": "EAGLE", "hint": "Ave de rapina majestosa", "category": "animals", "difficulty": 2},
    {"word": "SNAKE", "hint": "Réptil sem pernas", "category": "animals", "difficulty": 1},
    {"word": "TIGER", "hint": "Felino listrado laranja", "category": "animals", "difficulty": 1},
    {"word": "ZEBRA", "hint": "Equídeo listrado preto e branco", "category": "animals", "difficulty": 1},
    {"word": "DOLPHIN", "hint": "Mamífero marinho inteligente", "category": "animals", "difficulty": 2},
    {"word": "PENGUIN", "hint": "Ave marinha que não voa", "category": "animals", "difficulty": 2},
    {"word": "CROCODILE", "hint": "Grande réptil aquatico", "category": "animals", "difficulty": 3},
    {"word": "BUTTERFLY", "hint": "Inseto com asas coloridas", "category": "animals", "difficulty": 3},
    {"word": "ELEPHANT", "hint": "Maior terrestre com tromba", "category": "animals", "difficulty": 2},
    {"word": "GIRAFFE", "hint": "Animal de pescoço muito longo", "category": "animals", "difficulty": 2},
    {"word": "MONKEY", "hint": "Primata que imita humanos", "category": "animals", "difficulty": 1},
    {"word": "PARROT", "hint": "Ave colorida que fala", "category": "animals", "difficulty": 2},
    {"word": "RABBIT", "hint": "Coelho pequeno e peludo", "category": "animals", "difficulty": 1},
    {"word": "HORSE", "hint": "Equídeo domesticado para cavalgar", "category": "animals", "difficulty": 1},
    {"word": "SHARK", "hint": "Predador marinho temido", "category": "animals", "difficulty": 2},
    {"word": "CAMEL", "hint": "Animal do deserto com corcovas", "category": "animals", "difficulty": 2},
    {"word": "PANDA", "hint": "Urso preto e branco da China", "category": "animals", "difficulty": 1},
    {"word": "WALRUS", "hint": "Mamífero marinho com presas", "category": "animals", "difficulty": 3},
    {"word": "CHAMELEON", "hint": "Réptil que muda de cor", "category": "animals", "difficulty": 3},
    {"word": "PANTHER", "hint": "Felino escuro e silencioso", "category": "animals", "difficulty": 3},
    {"word": "FLAMINGO", "hint": "Ave rosa de pernas longas", "category": "animals", "difficulty": 3},
    {"word": "JAGUAR", "hint": "Felino das Américas", "category": "animals", "difficulty": 3},
    {"word": "BUFFALO", "hint": "Grande bovídeo selvagem", "category": "animals", "difficulty": 2},
    {"word": "CHEETAH", "hint": "Maior velocista do reino animal", "category": "animals", "difficulty": 3},

    # === COUNTRIES (30 words) ===
    {"word": "BRAZIL", "hint": "Maior país da América do Sul", "category": "countries", "difficulty": 1},
    {"word": "JAPAN", "hint": "País do sol nascente", "category": "countries", "difficulty": 1},
    {"word": "ITALY", "hint": "País da pizza e da pasta", "category": "countries", "difficulty": 1},
    {"word": "EGYPT", "hint": "País das pirâmides", "category": "countries", "difficulty": 1},
    {"word": "CHINA", "hint": "País mais populoso do mundo", "category": "countries", "difficulty": 1},
    {"word": "FRANCE", "hint": "País da Torre Eiffel", "category": "countries", "difficulty": 1},
    {"word": "SPAIN", "hint": "País da tauromaquia", "category": "countries", "difficulty": 1},
    {"word": "MEXICO", "hint": "País do taco e da sombrer", "category": "countries", "difficulty": 1},
    {"word": "CANADA", "hint": "Maior país do hemisfério norte", "category": "countries", "difficulty": 1},
    {"word": "GERMANY", "hint": "País da cerveja e da Oktoberfest", "category": "countries", "difficulty": 2},
    {"word": "PORTUGAL", "hint": "País vizinho da Espanha", "category": "countries", "difficulty": 2},
    {"word": "THAILAND", "hint": "País do sorriso no sudeste asiático", "category": "countries", "difficulty": 2},
    {"word": "AUSTRALIA", "hint": "País-continente da Oceania", "category": "countries", "difficulty": 2},
    {"word": "ARGENTINA", "hint": "País do Tango na América do Sul", "category": "countries", "difficulty": 2},
    {"word": "COLOMBIA", "hint": "País da América do Sul com duas costas", "category": "countries", "difficulty": 2},
    {"word": "NORWAY", "hint": "País escandinavo dos fiordes", "category": "countries", "difficulty": 2},
    {"word": "ICELAND", "hint": "Ilha vulcânica no Atlântico Norte", "category": "countries", "difficulty": 2},
    {"word": "VIETNAM", "hint": "País do sudeste asiático em forma de S", "category": "countries", "difficulty": 2},
    {"word": "BELGIUM", "hint": "País europeu famoso por chocolates", "category": "countries", "difficulty": 3},
    {"word": "MOROCCO", "hint": "País do norte da África", "category": "countries", "difficulty": 3},
    {"word": "SWEDEN", "hint": "País escandinavo do IKEA", "category": "countries", "difficulty": 3},
    {"word": "FINLAND", "hint": "País dos mil lagos", "category": "countries", "difficulty": 3},
    {"word": "KENYA", "hint": "País africano famoso por maratonas", "category": "countries", "difficulty": 2},
    {"word": "CHILE", "hint": "País longo e estreito na América do Sul", "category": "countries", "difficulty": 1},
    {"word": "PERU", "hint": "País dos incas e de Machu Picchu", "category": "countries", "difficulty": 1},
    {"word": "CUBA", "hint": "Ilha caribenha famosa pelo charuto", "category": "countries", "difficulty": 1},
    {"word": "INDIA", "hint": "País asiático do Taj Mahal", "category": "countries", "difficulty": 1},
    {"word": "RUSSIA", "hint": "Maior país do mundo em território", "category": "countries", "difficulty": 2},
    {"word": "TURKEY", "hint": "País que cruza Europa e Ásia", "category": "countries", "difficulty": 2},
    {"word": "GREECE", "hint": "Berço da democracia", "category": "countries", "difficulty": 2},

    # === FOOD (30 words) ===
    {"word": "BREAD", "hint": "Alimento feito com farinha fermentada", "category": "food", "difficulty": 1},
    {"word": "APPLE", "hint": "Fruta vermelha e crocante", "category": "food", "difficulty": 1},
    {"word": "RICE", "hint": "Cereal base da alimentação asiática", "category": "food", "difficulty": 1},
    {"word": "MILK", "hint": "Bebida branca de origem animal", "category": "food", "difficulty": 1},
    {"word": "FISH", "hint": "Alimento marinho rico em proteína", "category": "food", "difficulty": 1},
    {"word": "SALT", "hint": "Condimento essencial na cozinha", "category": "food", "difficulty": 1},
    {"word": "SUGAR", "hint": "Doce cristalino para adoçar", "category": "food", "difficulty": 1},
    {"word": "CHEESE", "hint": "Laticínio feito com leite coalhado", "category": "food", "difficulty": 2},
    {"word": "CHICKEN", "hint": "Ave doméstica e sua carne", "category": "food", "difficulty": 1},
    {"word": "NOODLE", "hint": "Macarrão em formato alongado", "category": "food", "difficulty": 2},
    {"word": "TOMATO", "hint": "Fruta usada como legume", "category": "food", "difficulty": 1},
    {"word": "POTATO", "hint": "Tubérculo versátil na cozinha", "category": "food", "difficulty": 1},
    {"word": "ONION", "hint": "Bulbo que faz chorar ao cortar", "category": "food", "difficulty": 1},
    {"word": "CARROT", "hint": "Raiz laranja rica em vitamina A", "category": "food", "difficulty": 1},
    {"word": "BANANA", "hint": "Fruta amarela e alongada", "category": "food", "difficulty": 1},
    {"word": "ORANGE", "hint": "Cítrica rica em vitamina C", "category": "food", "difficulty": 1},
    {"word": "GRAPE", "hint": "Fruta pequena para vinho", "category": "food", "difficulty": 2},
    {"word": "PEPPER", "hint": "Condimento picante ou legume", "category": "food", "difficulty": 2},
    {"word": "MANGO", "hint": "Fruta tropical suculenta", "category": "food", "difficulty": 2},
    {"word": "LEMON", "hint": "Cítrico ácido e amarelo", "category": "food", "difficulty": 1},
    {"word": "CREAM", "hint": "Parte gordurosa do leite", "category": "food", "difficulty": 2},
    {"word": "OLIVE", "hint": "Fruta para azeite", "category": "food", "difficulty": 2},
    {"word": "STEAK", "hint": "Corte de carne grelhada", "category": "food", "difficulty": 2},
    {"word": "BUTTER", "hint": "Laticínio amarelado para untar", "category": "food", "difficulty": 2},
    {"word": "COOKIE", "hint": "Biscoito doce e crocante", "category": "food", "difficulty": 2},
    {"word": "MUFFIN", "hint": "Bolo pequeno em formato de xícara", "category": "food", "difficulty": 3},
    {"word": "PASTRY", "hint": "Massa folhada recheada", "category": "food", "difficulty": 3},
    {"word": "WAFFLE", "hint": "Bolo grelhado com formatos", "category": "food", "difficulty": 3},
    {"word": "SPINACH", "hint": "Verde folhoso nutritivo", "category": "food", "difficulty": 3},
    {"word": "MUSHROOM", "hint": "Fungo comestível", "category": "food", "difficulty": 3},

    # === SPORTS (30 words) ===
    {"word": "SOCCER", "hint": "Esporte mais popular do mundo", "category": "sports", "difficulty": 1},
    {"word": "TENNIS", "hint": "Esporte de raquetes em quadra", "category": "sports", "difficulty": 1},
    {"word": "GOLF", "hint": "Esporte com bola e taco", "category": "sports", "difficulty": 1},
    {"word": "SWIM", "hint": "Locomoção na água", "category": "sports", "difficulty": 1},
    {"word": "RUN", "hint": "Locomoção rápida a pé", "category": "sports", "difficulty": 1},
    {"word": "JUDO", "hint": "Arte marcial japonesa", "category": "sports", "difficulty": 2},
    {"word": "RUGBY", "hint": "Esporte de contato com bola oval", "category": "sports", "difficulty": 2},
    {"word": "HOCKEY", "hint": "Esporte com taco e disco de gelo", "category": "sports", "difficulty": 2},
    {"word": "BOXING", "hint": "Esporte de combate com luvas", "category": "sports", "difficulty": 2},
    {"word": "SKATE", "hint": "Esporte sobre rodas ou gelo", "category": "sports", "difficulty": 1},
    {"word": "SURF", "hint": "Esporte sobre ondas do mar", "category": "sports", "difficulty": 1},
    {"word": "YOGA", "hint": "Prática de equilíbrio e flexibilidade", "category": "sports", "difficulty": 1},
    {"word": "CYCLING", "hint": "Esporte sobre duas rodas", "category": "sports", "difficulty": 2},
    {"word": "ARCHERY", "hint": "Tiro com arco e flecha", "category": "sports", "difficulty": 3},
    {"word": "FENCING", "hint": "Esporte com espada", "category": "sports", "difficulty": 3},
    {"word": "CLIMBING", "hint": "Escalada em rochas ou paredes", "category": "sports", "difficulty": 3},
    {"word": "KARATE", "hint": "Arte marcial com golpes precisos", "category": "sports", "difficulty": 2},
    {"word": "SAILING", "hint": "Esporte náutico com vela", "category": "sports", "difficulty": 3},
    {"word": "SPRINT", "hint": "Corrida de curta distância", "category": "sports", "difficulty": 2},
    {"word": "MEDAL", "hint": "Reconhecimento para o vencedor", "category": "sports", "difficulty": 1},
    {"word": "REFEREE", "hint": "Árbitro de uma partida", "category": "sports", "difficulty": 2},
    {"word": "GOAL", "hint": "Ponto marcado no jogo", "category": "sports", "difficulty": 1},
    {"word": "ARENA", "hint": "Local de competições esportivas", "category": "sports", "difficulty": 2},
    {"word": "TROPHY", "hint": "Taça para o campeão", "category": "sports", "difficulty": 2},
    {"word": "RECORD", "hint": "Marca histórica a ser batida", "category": "sports", "difficulty": 2},
    {"word": "MARATHON", "hint": "Corrida de longa distância", "category": "sports", "difficulty": 3},
    {"word": "VELOCITY", "hint": "Velocidade em movimentos esportivos", "category": "sports", "difficulty": 3},
    {"word": "STAMINA", "hint": "Resistência física do atleta", "category": "sports", "difficulty": 3},
    {"word": "COACH", "hint": "Treinador da equipe", "category": "sports", "difficulty": 1},
    {"word": "STADIUM", "hint": "Grandioso local para jogos", "category": "sports", "difficulty": 2},
]
